# Generated by Django 4.1.2 on 2022-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seputaruntirta', '0002_kelompok_alter_dosen_fakultas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok',
            name='keterangan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='kelompok',
            name='nama',
            field=models.IntegerField(),
        ),
    ]
