# Generated by Django 4.1.2 on 2022-10-08 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seputaruntirta', '0004_alter_dosen_fakultas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodi', models.IntegerField()),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='prodi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seputaruntirta.prodi'),
        ),
    ]
