# Generated by Django 4.1.2 on 2022-10-08 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seputaruntirta', '0005_prodi_alter_mahasiswa_prodi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prodi',
            old_name='prodi',
            new_name='nama',
        ),
    ]
